### ISSUE TITLE
Any test results for cornell and jacquard dataset?

### ISSUE THREAD

**Issue by ruinianxu** [dougsm/ggcnn#18]
Since I saw this repo supports Cornell and Jacquard dataset, I wonder if there already exists test performance on cornell and jacquard dataset somewhere.

**Comment by dougsm** [comment]
Hello,
We discuss the results on the datasets in this paper https://journals.sagepub.com/doi/full/10.1177/0278364919859066, however one of the main findings is that performance on the datasets doesn't necessarily equate to performance on a real robot.
