### ISSUE TITLE
question about experiment

### ISSUE THREAD

**Issue by ruinianxu** [dougsm/ggcnn#20]
Hi Morrison,

I want to do the same experiments to compare my work with yours. It is easy to get roughly the same household objects. But for adversarial objects, I wonder if you still have the stl files somewhere in your computer or you still remember the file name of 3d model such that I can easily find them from their databases.

Really appreciate your help.

**Comment by dougsm** [comment]
Hello,
All of the adversarial objects are available directly from the DexNet data: https://berkeley.app.box.com/s/w6bmvvkp399xtjpgskwq1cytkndmm7cn/folder/28003844491
