### ISSUE TITLE
evaluation.calculate_iou_match() is something wrong？

### ISSUE THREAD

**Issue by Cheniitt** [dougsm/ggcnn#23]
when training the ggcnn2, validating is always zero, but the loss is  Decreasing.

**Comment by Cheniitt** [comment]
![image](https://user-images.githubusercontent.com/48058507/70535559-4253f980-1b98-11ea-8049-7ac251d32be0.png)

**Comment by dougsm** [comment]
g'day @Cheniitt 

It definitely looks like there's something strange going on.  Can you provide more details?  What dataset are you using? What was the command you ran? If you run it with the `--vis` flag does it look like the network is learning properly?

**Comment by Cheniitt** [comment]
thanks for your reply @dougsm 
I used the jacquard dataset to train ggcnn2, run the command `python train_ggcnn.py --description training_example2 --network ggcnn2 --dataset jacquard --dataset-path <Path To Dataset> --vis`, when training with the flag `--vis`, it looks the network is learning properly.

**Comment by Cheniitt** [comment]
I found in https://github.com/dougsm/ggcnn/blob/ad48bc5f768fe0a9ba9fd47729638e0aed46e47b/utils/dataset_processing/grasp.py#L269,Whenever it always returns 0.
