### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by Steve-Mq** [dougsm/ggcnn#26]
Hello ! dougsm:
Thank you very much for the code you provided.I have a question why you choose the MSE function as the loss function.The input is an (depth) image, the ground truth is an image, how does the MSE function  ensure that the input is moving toward the label? Could you tell me your understanding?Thank you very much!
Any help will be much appreciated.

**Comment by dougsm** [comment]
Hi @Steve-Mq 
The MSE is acting pixelwise on the image-based labels at the output, so the loss is computed as the pixelwise ground truths and the output grasp map (set of images).  MSE is commonly used for reconstruction tasks.  I hope that helps.

**Comment by Steve-Mq** [comment]
@dougsm  Thank you very much!

**Comment by Steve-Mq** [comment]
@dougsm Thank you very much!
