### ISSUE TITLE
Pretrained weights for pytorch version

### ISSUE THREAD

**Issue by ancorasir** [dougsm/ggcnn#27]
Thanks the sharing the code with the community. Would you share the pretrained weights for pytorch as well?  I'd like to test trained model on images of novel object for example.

**Comment by dougsm** [comment]
Hi @ancorasir 
Sorry for the super slow reply, I completely missed this.  
Pretrained weights for some different conditions are available here: https://github.com/dougsm/ggcnn/releases/download/v1.0/ggcnn2_weights.zip

Note that if you have a specific application in mind, retraining for that scenario might provide better results, especiall aspects like field of view and data augmentation.

**Comment by trungpham2606** [comment]
@dougsm 
Seem there's something wrong that I cant load your saved file.
Can you specify the pytorch version you used for this project ?
