### ISSUE TITLE
About Cornell Grasping Dataset 

### ISSUE THREAD

**Issue by silver60229** [dougsm/ggcnn#35]
Hello, because the Cornell Grasping Dataset link is invalid, do you have any files you can provide to me? Thank you

**Comment by soongjian** [comment]
https://aistudio.baidu.com/aistudio/datasetdetail/27422

**Comment by Janx1913** [comment]
It can be found on Kaggle aswell https://www.kaggle.com/oneoneliu/cornell-grasp
