### ISSUE TITLE
How the network transforms the angle image into a specific angle?

### ISSUE THREAD

**Issue by lx-onism** [dougsm/ggcnn#4]
I know the ggcnn is input with a depth image and outputs three images. But I'm not sure how to use the three images to guide the robot when the robot need to grasp a specific part of something detected by it.
After all, one angel is needed when grasping,not an image.

**Comment by dougsm** [comment]
Hello,
Each pixel in the images represents a pose in 3D space.  To chose the grasping pose, we simply choose the pixel with the highest quality value, and create a pose from the corresponding depth and angle.  You can see this implemented for a Kinova robot in https://github.com/dougsm/ggcnn_kinova_grasping/blob/master/ggcnn_kinova_grasping/scripts/run_ggcnn.py#L135
