### ISSUE TITLE
How to use image-wise (IW) and object-wise (OW)Cornell data splits mentioned in the paper?Did you use data augment by default when you trained Cornell?Thank you.

### ISSUE THREAD

**Issue by thk8181** [dougsm/ggcnn#43]

**Comment by dougsm** [comment]
Hello,
The code here only supports image-wise split, which is what's quoted in the paper.  The data is augmented by default, with random crop and rotate (https://github.com/dougsm/ggcnn/blob/master/train_ggcnn.py#L202)

**Comment by thk8181** [comment]
Thank you for reply.
