### ISSUE TITLE
 grasp quality

### ISSUE THREAD

**Issue by wjydou** [dougsm/ggcnn#6]
Hello,I have completed the training, but how do I test the grasp quality ?

**Comment by dougsm** [comment]
Hello, after you have finished the training there is a script `evaluate.py` that will test the network.  There are some parameters you can set in the file before running it, e.g. the path to your trained models and how many grasps to evaluate per image.

**Comment by wjydou** [comment]
@dougsm Yes, I have already run evaluate.py, and the result of the output is a txt text.Some of the numbers of such output, I don’t know what that mean.So, can I detect the images that I have collected without running the robot to grab?
