### ISSUE TITLE
Plot output on a image

### ISSUE THREAD

**Issue by Marcelbgit** [dougsm/ggcnn#7]
Hello Doug,

thanks a lot for your code. I'm writing a thesis about the gg-cnn. Used only the half of the cornell Dataset because of lack of storage. It worked fine and I will test it with a own dataset. I saw the def plout_output in the evaluate.py. Can you tell me how to use that to plot the grasp position on one of the used image,pcd.. data?

Thanks for your help

**Comment by dougsm** [comment]
Hello, sorry about that. I've been meaning to document this better for ages.... 

I just added a docstring to that function so hopefully that will help.  It basically just takes the images from the dataset (rgb and depth) along with the output from the network.  Have a look, and if you still have questions just add another comment :-)
