### ISSUE TITLE
Incomplete files

### ISSUE THREAD

**Issue by youkenhou** [dougsm/ggcnn#9]
Thank you for your great work and the pytorch implementation! However it seems like there's some missing files such as `model` and `utils.data.get_dataset`. Could you please look into this problem? Thanks in advance.

**Comment by dougsm** [comment]
Whoops, sorry! I've added the models folder.  `get_dataset` is already there, it's in `__init__.py`

**Comment by youkenhou** [comment]
@dougsm Thanks a lot.
